[tools]
python = "3.12"

[env]
_.python.venv = '/Users/u1127189/Library/Caches/pypoetry/virtualenvs/eigakan-DPLh7QiV-py3.12'
DB_USER = "eigakan"
DB_PASSWORD = "doliprane"
DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "eigakan"
LOG_LEVEL = "DEBUG"
STATIC_DIR = "static"

[tasks.start-uvicorn]
run = "uvicorn eigakan.main:app --reload --log-level info"
alias = 'api'
description = "Start the web server." # mr api --port 8001

[tasks."db:conn"]
run = 'psql -d postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}'
alias = 'db'
description = 'Open a subshell into the database.'

[tasks."db:up"]
run = 'docker compose -f docker/compose.yaml up db -d'
alias = 'dbu'

[tasks."db:down"]
run = 'docker compose -f docker/compose.yaml down -v'
alias = 'dbd'

[tasks."db:reset"]
run = [
    'docker compose -f docker/compose.yaml down -v',
    'docker compose -f docker/compose.yaml up db -d'
]
alias = 'dbr'

[tasks."db:dump"]
run = 'pg_dump -d postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}  -s --schema api > db/api.sql'
alias = 'dbdump'
description = 'Dump the schema of the api schema.'
outputs = ['db/api.sql']