name: Python application
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        export POETRY_HOME=/opt/poetry
        python3 -m venv $POETRY_HOME
        $POETRY_HOME/bin/pip install poetry
        $POETRY_HOME/bin/poetry --version
        export PATH="${PATH}:${POETRY_HOME}/bin"
        poetry install --with quality --no-root
    - name: Lint
      run: |
        /opt/poetry/bin/poetry run ruff check 